services:
  - type: web
    name: zeiterfassung-app
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: zeiterfassung-db
          property: connectionString

databases:
  - name: zeiterfassung-db
    plan: basic-256mb
    databaseName: zeiterfassung
    user: zeiterfassung
